services:
  - type: web
    name: kuretaisyomachi-waiting-app-1
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: STORE_NAME
        sync: false
      - key: LINE_ADD_FRIEND_URL
        sync: false
